### ISSUE TITLE
Develop REST API endpoint for user registration/sign up

### ISSUE THREAD

**Issue by kludge7** [heikkkk/IDATT2105-Semester-Project-Backend#5]
When a new user wants to sign in/register this endpoint will make sure that the user data is stored in the database. It will also make sure that an existing user with the same username or email already exists, and if they do exist an error message will be sendt back to the client.

This includes making a service class for registration, a controller class and using the model classes. Could also here consider using a hashing alghoritm when storing the password of the user.

**Comment by heikkkk** [comment]
Implemented user sign-up/sign-in with hashing of user passwords
